---
name: CI checks

on: push

jobs:
  cargo-nursery:
    uses: Cosmian/reusable_workflows/.github/workflows/cargo-nursery.yml@main
    with:
      toolchain: stable
  wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose --features wasm_bindgen --target wasm32-unknown-unknown

  cargo-publish:
    needs:
      - cargo-nursery
      - wasm
    uses: Cosmian/reusable_workflows/.github/workflows/cargo-publish.yml@main
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    with:
      toolchain: stable
    secrets: inherit

  cleanup:
    needs:
      - cargo-publish
    uses: Cosmian/reusable_workflows/.github/workflows/cleanup_cache.yml@main
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    secrets: inherit
